import Head from 'next/head';
import { useState } from 'react';
import useSWR from 'swr';

import PokemonLink from '../components/PokemonLink';
import { Pokemon } from '../types/pokemon';
import { fetcher } from '../utils/fetcher';


export default function Home() {
  const [offset, setOffset] = useState(0);
  const [limit, setLimit] = useState(10);
  const { data, error, isLoading } = useSWR<{ results: Pokemon[]}>(`https://pokeapi.co/api/v2/pokemon?limit=${limit}&offset=${offset}`, fetcher);

  const handleOptionSelection = (e) => {
    setLimit(Number(e.target.value));
    setOffset(0);
  }
  
  if(error) {
    return (<pre>{JSON.stringify(error, null, 2)}</pre>)
  }
  
  if(isLoading) {
    return (<span>Loading...</span>)
  }

  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          {
            data.results.map((pokemon) => <PokemonLink key={pokemon.name} pokemonName={ pokemon.name }></PokemonLink>)
          }
        </section>
        <br />
        <button type="button" disabled={offset === 0} onClick={() => setOffset(offset - limit)}>Previous</button>
        <button type="button" onClick={() => setOffset(offset + limit)}>Next</button>
        <select defaultValue={limit} onChange={(e) => handleOptionSelection(e)}>
          <option value={10}>10</option>
          <option value={50}>50</option>
          <option value={151}>151</option>
        </select>
      </main>
    </>
  )
}
